site_name: luq

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github  # optional, for GitHub icon

repo_url: https://github.com/AlexanderVNikitin/luq
repo_name: AlexanderVNikitin/luq

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - API Reference: reference.md

